version: 2.1

orbs:
  ruby: circleci/ruby@1.4.0
  heroku: circleci/heroku@1.2.6

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.2
    working_directory: ~/my-docker-test-2/back
    steps:
      - checkout:
          path: ~/my-docker-test-2
      - run:
          name: bundler install
          command: gem install bundler -v 2.3.7
      - run:
          name: bundle install
          command: bundle install
  test:
    docker:
      - image: cimg/ruby:3.1.2
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: myapp_test
    environment:
      BUNDLE_JOBS: '3'
      BUNDLE_RETRY: '3'
      APP_DATABASE_HOST: '127.0.0.1'
      RAILS_ENV: test
    working_directory: ~/my-docker-test-2/back
    steps:
      - checkout:
          path: ~/my-docker-test-2
      - run:
          name: bundler install
          command: gem install bundler -v 2.3.7
      - run:
          name: bundle install
          command: bundle install
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run:
          name: test
          command: bundle exec rake test
  deploy:
    docker:
      - image: cimg/ruby:3.1.2
    working_directory: ~/my-docker-test-2
    steps:
      - checkout:
          path: ~/my-docker-test-2
      - heroku/install
      - run:
          name: heroku login
          command: heroku container:login
      - run:
          name: export
          command: export DOCKER_CLI_EXPERIMENTAL=enabled
      - run:
          name: docker images
          command: sudo docker images
      - run:
          name: build docker image
          command: docker buildx build . --platform linux/amd64 -t takuya/my-docker-test-2-mtakk:latest
      - run:
          name: docker images
          command: sudo docker images
      - run:
          name: docker tag
          command: docker tag takuya/my-docker-test-2-mtakk registry.heroku.com/my-docker-test-2-mtakk/web
      - run:
          name: docker push
          command: docker push registry.heroku.com/my-docker-test-2-mtakk/web
      - run:
          name: push docker image
          command: sudo docker push registry.heroku.com/my-docker-test-2-mtakk/web
      - run:
          name: release docker image
          command: heroku container:release web -a $HEROKU_APP_NAME
      - run:
          name: database setup
          command: heroku run bundle exec rake db:migrate RAILS_ENV=production -a $HEROKU_APP_NAME

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main

